# Generated by Django 5.0.1 on 2024-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_1', models.IntegerField()),
                ('int_2', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('str_1', models.CharField(max_length=200)),
                ('str_2', models.CharField(max_length=200)),
                ('hits', models.IntegerField()),
            ],
        ),
    ]
