# Generated by Django 5.0.1 on 2024-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FizzBuzzApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='hits',
            field=models.IntegerField(null=True),
        ),
    ]
