# Generated by Django 5.0.1 on 2024-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FizzBuzzApplication', '0002_alter_parameter_hits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='int_1',
            new_name='int1',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='int_2',
            new_name='int2',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='str_1',
            new_name='str1',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='str_2',
            new_name='str2',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='hits',
            field=models.IntegerField(),
        ),
    ]
