# Generated by Django 5.0.1 on 2024-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FizzBuzzApplication', '0003_rename_int_1_parameter_int1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='hits',
            field=models.IntegerField(default=1),
        ),
    ]
